version: "3.7"
services:
  frontend:
    image: zorro909/blankdiscordbot:${TAG}
    volumes:
     - blankBotConfig:/blankbot/config
    networks:
     - blank-bot-bridge
    environment:
      MYSQL_HOST: jdbc:mysql://${MYSQL_HOST}
      MYQSL_HOSTNAME: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DISCORD_AUTH_TOKEN: ${DISCORD_AUTH_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      INFURA_PROJECT_ID: ${INFURA_PROJECT_ID}
      ETHERSCAN_APIKEY: ${ETHERSCAN_APIKEY}
  mysql:
    image: "mariadb"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - blank-bot-bridge
    volumes:
      - blankBotMysqlData:/var/lib/mysql
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
     - blank-bot-bridge
    ports:
      - 22181:2181
  broker: 
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
     - /blankbot/kafka/logs:/kafka/logs
    networks:
     - blank-bot-bridge
networks:
  blank-bot-bridge:
    driver: bridge
volumes:
  blankBotMysqlData:
  blankBotConfig: