on: 
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Tag'
        required: true

jobs:
  deploy:
    name: Release Docker Container
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and publish new Docker Container Release
      run: cd dockerBuild && ./releaseDockerVersion.sh ${{ github.event.inputs.release-version }}
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}