on: workflow_call

jobs:
  deploy:
    name: Development Docker Container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and publish Dev Docker Container
      run: cd dockerBuild && ./deployTaggedBuild.sh
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}