on: workflow_dispatch

jobs:
  deploy:
    name: Development Docker Container
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and publish Dev Docker Container
      run: cd dockerBuild && ./deployTaggedBuild.sh
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}