on: push
  
jobs:
    sonar:        
        name: Test - SonarCloud Scan
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: '0'
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
            - name: SonarCloud Scan
              run: mvn -B clean verify install -Pcoverage -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}