on: push
  
jobs:
    sonar:        
        name: Test - SonarCloud Scan
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: '0'
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'temurin'
            - name: SonarCloud Scan discord-library
              working-directory: discord-library
              run: mvn -B clean verify -Pcoverage -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: SonarCloud Scan funplace
              working-directory: funplace
              run: mvn -B clean verify -Pcoverage -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: SonarCloud Scan discord-wallet-connection
              working-directory: discord-wallet-connection            
              run: mvn -B clean verify -Pcoverage -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: SonarCloud Scan nft-sales
              working-directory: nft-sales            
              run: mvn -B clean verify -Pcoverage -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
            - name: SonarCloud Scan blankdiscordbot-core
              working-directory: blankdiscordbot-core            
              run: mvn -B clean verify -Pcoverage -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: SonarCloud Scan discord-commands
              working-directory: discord-commands           
              run: mvn -B clean verify -Pcoverage -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: SonarCloud Scan discord-games
              working-directory: discord-games           
              run: mvn -B clean verify -Pcoverage -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
