name: Validate application.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: YAML Schema Validator
      uses: nwisbeta/validate-yaml-schema@v2.0.0
    - run: |
        if $(jq "split(\",\") | all(. != \"src/main/resources/application.yml\")" <<< '"${{ steps.validate-yaml-schema.outputs.validFiles }}"'); then
          echo "application.yml was not validated"
          exit 1
        fi
      shell: bash